# **Fundamentos de Inteligencia Artificial**

### Juan Dario Rodas - jdrodas@hotmail.com
### Enero 10 de 2026


# Fundamentos de NumPy

## 1. Introducción

### ¿Qué es NumPy?

**NumPy** (Numerical Python) es la librería fundamental para computación científica en Python. Proporciona:

- **Arrays** (arreglos) multidimensionales eficientes
- Funciones matemáticas de alto rendimiento
- Herramientas para álgebra lineal, transformaciones y estadística

### ¿Por qué NumPy es crucial en IA y Machine Learning?

En Inteligencia Artificial trabajamos constantemente con grandes volúmenes de datos numéricos:
- **Imágenes**: matrices de píxeles
- **Datos tabulares**: filas y columnas de características (features)
- **Redes neuronales**: operaciones matriciales masivas

NumPy permite realizar estas operaciones de manera:
1. **Eficiente**: Significativamente más rápido que listas de Python puras
2. **Concisa**: Menos código, más legible
3. **Vectorizada**: Operaciones sobre conjuntos completos de datos sin loops explícitos

In [2]:
# Importar NumPy (convención estándar: alias 'np')
import numpy as np

# Verificar la versión instalada
print(f"Versión de NumPy: {np.__version__}")

print("\n" + "="*60)
print("COMPARACIÓN: Listas de Python vs Arrays de NumPy")
print("="*60)

# Ejemplo con listas de Python
lista_python = [1, 2, 3, 4, 5]
print(f"\nLista de Python: {lista_python}")
print(f"Tipo: {type(lista_python)}")

# Mismo ejemplo con NumPy array
array_numpy = np.array([1, 2, 3, 4, 5])
print(f"\nArray de NumPy: {array_numpy}")
print(f"Tipo: {type(array_numpy)}")

print("\n" + "-"*60)
print("Operación: Multiplicar cada elemento por 2")
print("-"*60)

# Con listas de Python: necesitamos un loop
resultado_lista = [x * 2 for x in lista_python]
print(f"Lista Python (con list comprehension): {resultado_lista}")

# Con NumPy: operación vectorizada (sin loop explícito)
resultado_array = array_numpy * 2
print(f"Array NumPy (vectorizado): {resultado_array}")



Versión de NumPy: 2.0.2

COMPARACIÓN: Listas de Python vs Arrays de NumPy

Lista de Python: [1, 2, 3, 4, 5]
Tipo: <class 'list'>

Array de NumPy: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>

------------------------------------------------------------
Operación: Multiplicar cada elemento por 2
------------------------------------------------------------
Lista Python (con list comprehension): [2, 4, 6, 8, 10]
Array NumPy (vectorizado): [ 2  4  6  8 10]


## 2. Fundamentos de Arrays (Arreglos)

### ¿Qué es un Array de NumPy?

Un **array** (arreglo) es una estructura de datos que almacena elementos del mismo tipo en una grilla multidimensional. A diferencia de las listas de Python, los arrays de NumPy:

- Son **homogéneos**: todos los elementos son del mismo tipo de dato
- Son **densos**: ocupan un bloque continuo de memoria
- Soportan **operaciones vectorizadas**: aplicar operaciones a todos los elementos simultáneamente

### Dimensiones de Arrays

- **1D (una dimensión)**: Vector - similar a una lista `[1, 2, 3, 4]`
- **2D (dos dimensiones)**: Matriz - similar a una tabla con filas y columnas
- **3D o más**: Tensores (tensors) - útiles para imágenes, videos, datos complejos

### Formas Comunes de Crear Arrays

Existen múltiples funciones para crear arrays según nuestras necesidades:

| Función | Descripción |
|---------|-------------|
| `np.array()` | Crea un array desde una lista o tupla |
| `np.zeros()` | Array lleno de ceros |
| `np.ones()` | Array lleno de unos |
| `np.arange()` | Array con secuencia numérica (similar a `range()`) |
| `np.linspace()` | Array con N valores equiespaciados entre dos números |
| `np.random.rand()` | Array con valores aleatorios entre 0 y 1 |

In [3]:
print("="*60)
print("CREACIÓN DE ARRAYS")
print("="*60)

# 1. Crear array desde una lista
print("\n1. Array desde lista:")
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"   {arr_1d}")

# 2. Array 2D (matriz) desde lista de listas
print("\n2. Array 2D (matriz):")
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

# 3. Array de ceros
print("\n3. Array de ceros (3x4):")
zeros = np.zeros((3, 4))
print(zeros)

# 4. Array de unos
print("\n4. Array de unos (2x3):")
ones = np.ones((2, 3))
print(ones)

# 5. Secuencia con arange (similar a range())
print("\n5. Secuencia con arange (0 a 10, paso 2):")
secuencia = np.arange(0, 10, 2)
print(f"   {secuencia}")

# 6. Valores equiespaciados con linspace
print("\n6. Linspace (5 valores entre 0 y 1):")
equiespaciado = np.linspace(0, 1, 5)
print(f"   {equiespaciado}")

# 7. Array aleatorio (útil para inicializar pesos en redes neuronales)
print("\n7. Array aleatorio 2x3:")
aleatorio = np.random.rand(2, 3)
print(aleatorio)

CREACIÓN DE ARRAYS

1. Array desde lista:
   [1 2 3 4 5]

2. Array 2D (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3. Array de ceros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

4. Array de unos (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

5. Secuencia con arange (0 a 10, paso 2):
   [0 2 4 6 8]

6. Linspace (5 valores entre 0 y 1):
   [0.   0.25 0.5  0.75 1.  ]

7. Array aleatorio 2x3:
[[0.67640551 0.24278663 0.32471766]
 [0.77819852 0.1692331  0.517922  ]]


In [5]:
print("="*60)
print("PROPIEDADES DE ARRAYS")
print("="*60)

# Creamos un array de ejemplo
ejemplo = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

print("\nArray de ejemplo:")
print(ejemplo)

print("\n" + "-"*60)
print("Propiedades básicas:")
print("-"*60)

# shape: forma/dimensiones del array (filas, columnas, ...)
print(f"\n📐 shape (forma): {ejemplo.shape}")
print(f"   → {ejemplo.shape[0]} filas, {ejemplo.shape[1]} columnas")

# ndim: número de dimensiones
print(f"\n📊 ndim (número de dimensiones): {ejemplo.ndim}")

# size: número total de elementos
print(f"\n🔢 size (tamaño total): {ejemplo.size}")
print(f"   → {ejemplo.shape[0]} × {ejemplo.shape[1]} = {ejemplo.size} elementos")

# dtype: tipo de dato de los elementos
print(f"\n🏷️  dtype (tipo de dato): {ejemplo.dtype}")

# nbytes: memoria ocupada en bytes
print(f"\n💾 nbytes (memoria en bytes): {ejemplo.nbytes}")

print("\n" + "="*60)
print("COMPARACIÓN: Arrays 1D vs 2D vs 3D")
print("="*60)

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("\n1D (Vector):")
print(arr_1d)
print(f"→ shape: {arr_1d.shape}, ndim: {arr_1d.ndim}")

print("\n2D (Matriz):")
print(arr_2d)
print(f"→ shape: {arr_2d.shape}, ndim: {arr_2d.ndim}")

print("\n3D (Tensor):")
print(arr_3d)
print(f"→ shape: {arr_3d.shape}, ndim: {arr_3d.ndim}")

PROPIEDADES DE ARRAYS

Array de ejemplo:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

------------------------------------------------------------
Propiedades básicas:
------------------------------------------------------------

📐 shape (forma): (3, 4)
   → 3 filas, 4 columnas

📊 ndim (número de dimensiones): 2

🔢 size (tamaño total): 12
   → 3 × 4 = 12 elementos

🏷️  dtype (tipo de dato): int64

💾 nbytes (memoria en bytes): 96

COMPARACIÓN: Arrays 1D vs 2D vs 3D

1D (Vector):
[1 2 3]
→ shape: (3,), ndim: 1

2D (Matriz):
[[1 2]
 [3 4]]
→ shape: (2, 2), ndim: 2

3D (Tensor):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
→ shape: (2, 2, 2), ndim: 3
