# **Fundamentos de Inteligencia Artificial**

### Juan Dario Rodas - jdrodas@hotmail.com
### Enero 10 de 2026


# **Fundamentos de NumPy**

## **1. Introducción**

### ¿Qué es NumPy?

**NumPy** (Numerical Python) es la librería fundamental para computación científica en Python. Proporciona:

- **Arrays** (arreglos) multidimensionales eficientes
- Funciones matemáticas de alto rendimiento
- Herramientas para álgebra lineal, transformaciones y estadística

### ¿Por qué NumPy es crucial en IA y Machine Learning?

En Inteligencia Artificial trabajamos constantemente con grandes volúmenes de datos numéricos:
- **Imágenes**: matrices de píxeles
- **Datos tabulares**: filas y columnas de características (features)
- **Redes neuronales**: operaciones matriciales masivas

NumPy permite realizar estas operaciones de manera:
1. **Eficiente**: Significativamente más rápido que listas de Python puras
2. **Concisa**: Menos código, más legible
3. **Vectorizada**: Operaciones sobre conjuntos completos de datos sin loops explícitos

In [2]:
# Importar NumPy (convención estándar: alias 'np')
import numpy as np

# Verificar la versión instalada
print(f"Versión de NumPy: {np.__version__}")

print("\n" + "="*60)
print("COMPARACIÓN: Listas de Python vs Arrays de NumPy")
print("="*60)

# Ejemplo con listas de Python
lista_python = [1, 2, 3, 4, 5]
print(f"\nLista de Python: {lista_python}")
print(f"Tipo: {type(lista_python)}")

# Mismo ejemplo con NumPy array
array_numpy = np.array([1, 2, 3, 4, 5])
print(f"\nArray de NumPy: {array_numpy}")
print(f"Tipo: {type(array_numpy)}")

print("\n" + "-"*60)
print("Operación: Multiplicar cada elemento por 2")
print("-"*60)

# Con listas de Python: necesitamos un loop
resultado_lista = [x * 2 for x in lista_python]
print(f"Lista Python (con list comprehension): {resultado_lista}")

# Con NumPy: operación vectorizada (sin loop explícito)
resultado_array = array_numpy * 2
print(f"Array NumPy (vectorizado): {resultado_array}")



Versión de NumPy: 2.0.2

COMPARACIÓN: Listas de Python vs Arrays de NumPy

Lista de Python: [1, 2, 3, 4, 5]
Tipo: <class 'list'>

Array de NumPy: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>

------------------------------------------------------------
Operación: Multiplicar cada elemento por 2
------------------------------------------------------------
Lista Python (con list comprehension): [2, 4, 6, 8, 10]
Array NumPy (vectorizado): [ 2  4  6  8 10]


## **2. Fundamentos de Arrays (Arreglos)**

### ¿Qué es un Array de NumPy?

Un **array** (arreglo) es una estructura de datos que almacena elementos del mismo tipo en una grilla multidimensional. A diferencia de las listas de Python, los arrays de NumPy:

- Son **homogéneos**: todos los elementos son del mismo tipo de dato
- Son **densos**: ocupan un bloque continuo de memoria
- Soportan **operaciones vectorizadas**: aplicar operaciones a todos los elementos simultáneamente

### Dimensiones de Arrays

- **1D (una dimensión)**: Vector - similar a una lista `[1, 2, 3, 4]`
- **2D (dos dimensiones)**: Matriz - similar a una tabla con filas y columnas
- **3D o más**: Tensores (tensors) - útiles para imágenes, videos, datos complejos

### Formas Comunes de Crear Arrays

Existen múltiples funciones para crear arrays según nuestras necesidades:

| Función | Descripción |
|---------|-------------|
| `np.array()` | Crea un array desde una lista o tupla |
| `np.zeros()` | Array lleno de ceros |
| `np.ones()` | Array lleno de unos |
| `np.arange()` | Array con secuencia numérica (similar a `range()`) |
| `np.linspace()` | Array con N valores equiespaciados entre dos números |
| `np.random.rand()` | Array con valores aleatorios entre 0 y 1 |

In [3]:
print("="*60)
print("CREACIÓN DE ARRAYS")
print("="*60)

# 1. Crear array desde una lista
print("\n1. Array desde lista:")
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"   {arr_1d}")

# 2. Array 2D (matriz) desde lista de listas
print("\n2. Array 2D (matriz):")
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

# 3. Array de ceros
print("\n3. Array de ceros (3x4):")
zeros = np.zeros((3, 4))
print(zeros)

# 4. Array de unos
print("\n4. Array de unos (2x3):")
ones = np.ones((2, 3))
print(ones)

# 5. Secuencia con arange (similar a range())
print("\n5. Secuencia con arange (0 a 10, paso 2):")
secuencia = np.arange(0, 10, 2)
print(f"   {secuencia}")

# 6. Valores equiespaciados con linspace
print("\n6. Linspace (5 valores entre 0 y 1):")
equiespaciado = np.linspace(0, 1, 5)
print(f"   {equiespaciado}")

# 7. Array aleatorio (útil para inicializar pesos en redes neuronales)
print("\n7. Array aleatorio 2x3:")
aleatorio = np.random.rand(2, 3)
print(aleatorio)

CREACIÓN DE ARRAYS

1. Array desde lista:
   [1 2 3 4 5]

2. Array 2D (matriz):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3. Array de ceros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

4. Array de unos (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

5. Secuencia con arange (0 a 10, paso 2):
   [0 2 4 6 8]

6. Linspace (5 valores entre 0 y 1):
   [0.   0.25 0.5  0.75 1.  ]

7. Array aleatorio 2x3:
[[0.77125027 0.41360511 0.31255574]
 [0.28421287 0.81383279 0.87341526]]


In [4]:
print("="*60)
print("PROPIEDADES DE ARRAYS")
print("="*60)

# Creamos un array de ejemplo
ejemplo = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

print("\nArray de ejemplo:")
print(ejemplo)

print("\n" + "-"*60)
print("Propiedades básicas:")
print("-"*60)

# shape: forma/dimensiones del array (filas, columnas, ...)
print(f"\n📐 shape (forma): {ejemplo.shape}")
print(f"   → {ejemplo.shape[0]} filas, {ejemplo.shape[1]} columnas")

# ndim: número de dimensiones
print(f"\n📊 ndim (número de dimensiones): {ejemplo.ndim}")

# size: número total de elementos
print(f"\n🔢 size (tamaño total): {ejemplo.size}")
print(f"   → {ejemplo.shape[0]} × {ejemplo.shape[1]} = {ejemplo.size} elementos")

# dtype: tipo de dato de los elementos
print(f"\n🏷️  dtype (tipo de dato): {ejemplo.dtype}")

# nbytes: memoria ocupada en bytes
print(f"\n💾 nbytes (memoria en bytes): {ejemplo.nbytes}")

print("\n" + "="*60)
print("COMPARACIÓN: Arrays 1D vs 2D vs 3D")
print("="*60)

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("\n1D (Vector):")
print(arr_1d)
print(f"→ shape: {arr_1d.shape}, ndim: {arr_1d.ndim}")

print("\n2D (Matriz):")
print(arr_2d)
print(f"→ shape: {arr_2d.shape}, ndim: {arr_2d.ndim}")

print("\n3D (Tensor):")
print(arr_3d)
print(f"→ shape: {arr_3d.shape}, ndim: {arr_3d.ndim}")

PROPIEDADES DE ARRAYS

Array de ejemplo:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

------------------------------------------------------------
Propiedades básicas:
------------------------------------------------------------

📐 shape (forma): (3, 4)
   → 3 filas, 4 columnas

📊 ndim (número de dimensiones): 2

🔢 size (tamaño total): 12
   → 3 × 4 = 12 elementos

🏷️  dtype (tipo de dato): int64

💾 nbytes (memoria en bytes): 96

COMPARACIÓN: Arrays 1D vs 2D vs 3D

1D (Vector):
[1 2 3]
→ shape: (3,), ndim: 1

2D (Matriz):
[[1 2]
 [3 4]]
→ shape: (2, 2), ndim: 2

3D (Tensor):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
→ shape: (2, 2, 2), ndim: 3


## **3. Indexing (Indexación) y Slicing (Rebanado)**

### **Indexación**

El **indexing** (indexación) nos permite acceder a elementos específicos de un array. NumPy usa indexación basada en cero (el primer elemento tiene índice 0), similar a las listas de Python.

**Sintaxis básica:**
- Arrays 1D: `array[índice]`
- Arrays 2D: `array[fila, columna]`
- Arrays 3D: `array[profundidad, fila, columna]`

### **Rebanado**

El **slicing** permite extraer sub-arrays (sub-arreglos) usando la sintaxis `inicio:fin:paso`

**Reglas importantes:**
- `inicio` es inclusivo
- `fin` es exclusivo
- Si se omite `inicio`, comienza desde 0
- Si se omite `fin`, va hasta el final
- Si se omite `paso`, el paso es 1

### **Indexación booleana (Boolean Indexing)**

Una técnica que permite filtrar datos usando condiciones lógicas. Muy útil en preprocesamiento de datos para IA.

**Ejemplo conceptual:**
```python
array[array > 5]  # Obtiene todos los elementos mayores que 5
```

In [5]:
print("="*60)
print("INDEXING (INDEXACIÓN)")
print("="*60)

# Array 1D
arr_1d = np.array([10, 20, 30, 40, 50])
print("\nArray 1D:", arr_1d)
print(f"Primer elemento (índice 0): {arr_1d[0]}")
print(f"Último elemento (índice -1): {arr_1d[-1]}")
print(f"Tercer elemento (índice 2): {arr_1d[2]}")

# Array 2D
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("\nArray 2D:")
print(arr_2d)
print(f"Elemento en fila 0, columna 2: {arr_2d[0, 2]}")
print(f"Elemento en fila 2, columna 3: {arr_2d[2, 3]}")
print(f"Primera fila completa: {arr_2d[0]}")

print("\n" + "="*60)
print("SLICING (REBANADO)")
print("="*60)

print("\nArray 1D:", arr_1d)
print(f"Primeros 3 elementos [0:3]: {arr_1d[0:3]}")
print(f"Del índice 2 al final [2:]: {arr_1d[2:]}")
print(f"Hasta el índice 3 [:3]: {arr_1d[:3]}")
print(f"Cada 2 elementos [::2]: {arr_1d[::2]}")

print("\nArray 2D:")
print(arr_2d)
print("\nPrimeras 2 filas, todas las columnas:")
print(arr_2d[0:2, :])
print("\nTodas las filas, primeras 2 columnas:")
print(arr_2d[:, 0:2])
print("\nFilas 1 y 2, columnas 2 y 3:")
print(arr_2d[1:3, 2:4])

print("\n" + "="*60)
print("INDEXING BOOLEANO (BOOLEAN INDEXING)")
print("="*60)

datos = np.array([5, 12, 3, 18, 7, 25, 9])
print(f"\nArray original: {datos}")

# Crear máscara booleana (boolean mask)
mascara = datos > 10
print(f"Máscara (datos > 10): {mascara}")

# Aplicar la máscara para filtrar
filtrado = datos[mascara]
print(f"Elementos mayores que 10: {filtrado}")

# Forma compacta (más común)
print(f"Elementos entre 5 y 15: {datos[(datos >= 5) & (datos <= 15)]}")

INDEXING (INDEXACIÓN)

Array 1D: [10 20 30 40 50]
Primer elemento (índice 0): 10
Último elemento (índice -1): 50
Tercer elemento (índice 2): 30

Array 2D:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elemento en fila 0, columna 2: 3
Elemento en fila 2, columna 3: 12
Primera fila completa: [1 2 3 4]

SLICING (REBANADO)

Array 1D: [10 20 30 40 50]
Primeros 3 elementos [0:3]: [10 20 30]
Del índice 2 al final [2:]: [30 40 50]
Hasta el índice 3 [:3]: [10 20 30]
Cada 2 elementos [::2]: [10 30 50]

Array 2D:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Primeras 2 filas, todas las columnas:
[[1 2 3 4]
 [5 6 7 8]]

Todas las filas, primeras 2 columnas:
[[ 1  2]
 [ 5  6]
 [ 9 10]]

Filas 1 y 2, columnas 2 y 3:
[[ 7  8]
 [11 12]]

INDEXING BOOLEANO (BOOLEAN INDEXING)

Array original: [ 5 12  3 18  7 25  9]
Máscara (datos > 10): [False  True False  True False  True False]
Elementos mayores que 10: [12 18 25]
Elementos entre 5 y 15: [ 5 12  7  9]


## **Ejercicio 1: Manipulación y Extracción de Datos**

### Contexto

Imagina que tienes datos de temperaturas registradas durante una semana en 4 ciudades diferentes. Cada fila representa una ciudad y cada columna un día de la semana.

### Instrucciones

Dado el siguiente array de temperaturas:
```python
temperaturas = np.array([[22, 24, 23, 25, 26, 24, 23],  # Ciudad A
                         [18, 19, 20, 19, 21, 20, 19],  # Ciudad B
                         [30, 32, 31, 33, 34, 32, 31],  # Ciudad C
                         [15, 16, 15, 17, 18, 16, 15]]) # Ciudad D
```

**Tareas a realizar:**

1. Extraer las temperaturas de la Ciudad C (fila 2)
2. Extraer las temperaturas del miércoles (columna 2, recordar que empieza en 0)
3. Extraer las temperaturas del fin de semana (columnas 5 y 6) para todas las ciudades
4. Encontrar todos los días donde alguna ciudad tuvo temperatura mayor a 30 grados




In [6]:
print("="*60)
print("SOLUCIÓN - EJERCICIO 1")
print("="*60)

# Datos del ejercicio
temperaturas = np.array([[22, 24, 23, 25, 26, 24, 23],  # Ciudad A
                         [18, 19, 20, 19, 21, 20, 19],  # Ciudad B
                         [30, 32, 31, 33, 34, 32, 31],  # Ciudad C
                         [15, 16, 15, 17, 18, 16, 15]]) # Ciudad D

print("\nArray de temperaturas (Ciudades × Días):")
print(temperaturas)
print(f"Shape: {temperaturas.shape} → 4 ciudades, 7 días")

print("\n" + "-"*60)
print("Tarea 1: Temperaturas de la Ciudad C")
print("-"*60)
ciudad_c = temperaturas[2]
print(f"Ciudad C: {ciudad_c}")

print("\n" + "-"*60)
print("Tarea 2: Temperaturas del miércoles (columna 2)")
print("-"*60)
miercoles = temperaturas[:, 2]
print(f"Miércoles (todas las ciudades): {miercoles}")

print("\n" + "-"*60)
print("Tarea 3: Temperaturas del fin de semana (columnas 5 y 6)")
print("-"*60)
fin_semana = temperaturas[:, 5:7]
print("Fin de semana:")
print(fin_semana)

print("\n" + "-"*60)
print("Tarea 4: Temperaturas mayores a 30 grados")
print("-"*60)
mayores_30 = temperaturas[temperaturas > 30]
print(f"Temperaturas > 30°: {mayores_30}")


SOLUCIÓN - EJERCICIO 1

Array de temperaturas (Ciudades × Días):
[[22 24 23 25 26 24 23]
 [18 19 20 19 21 20 19]
 [30 32 31 33 34 32 31]
 [15 16 15 17 18 16 15]]
Shape: (4, 7) → 4 ciudades, 7 días

------------------------------------------------------------
Tarea 1: Temperaturas de la Ciudad C
------------------------------------------------------------
Ciudad C: [30 32 31 33 34 32 31]

------------------------------------------------------------
Tarea 2: Temperaturas del miércoles (columna 2)
------------------------------------------------------------
Miércoles (todas las ciudades): [23 20 31 15]

------------------------------------------------------------
Tarea 3: Temperaturas del fin de semana (columnas 5 y 6)
------------------------------------------------------------
Fin de semana:
[[24 23]
 [20 19]
 [32 31]
 [16 15]]

------------------------------------------------------------
Tarea 4: Temperaturas mayores a 30 grados
---------------------------------------------------------

## **4. Operaciones y Funciones**

### **Operaciones Elemento a Elemento (Element-wise Operations)**

NumPy permite realizar operaciones aritméticas directamente sobre arrays completos. Estas operaciones se aplican **elemento por elemento** (element-wise):

- Suma: `array1 + array2`
- Resta: `array1 - array2`
- Multiplicación: `array1 * array2`
- División: `array1 / array2`
- Potencia: `array ** n`

**Importante:** La multiplicación `*` es elemento a elemento, NO es multiplicación matricial.

### **Funciones Universales (Universal Functions - ufuncs)**

Las **ufuncs** son funciones que operan elemento por elemento sobre arrays. Ejemplos comunes:

| Función | Descripción |
|---------|-------------|
| `np.sqrt()` | Raíz cuadrada |
| `np.exp()` | Exponencial (e^x) |
| `np.log()` | Logaritmo natural |
| `np.sin()`, `np.cos()` | Funciones trigonométricas |
| `np.abs()` | Valor absoluto |

### **Funciones de Agregación (Aggregation Functions)**

Estas funciones reducen un array a un valor único (o a valores por eje):

| Función | Descripción |
|---------|-------------|
| `np.sum()` | Suma de todos los elementos |
| `np.mean()` | Promedio (media aritmética) |
| `np.std()` | Desviación estándar (standard deviation) |
| `np.min()`, `np.max()` | Mínimo y máximo |
| `np.argmin()`, `np.argmax()` | Índice del mínimo y máximo |

### **Operaciones por Ejes (Axis)**

El parámetro `axis` controla la dirección de la operación:
- `axis=0`: Operación a lo largo de las filas (columna por columna)
- `axis=1`: Operación a lo largo de las columnas (fila por fila)
- `axis=None` (default): Operación sobre todo el array

In [7]:
print("="*60)
print("OPERACIONES ELEMENTO A ELEMENTO")
print("="*60)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print(f"\nArray 1: {arr1}")
print(f"Array 2: {arr2}")

print(f"\nSuma (arr1 + arr2): {arr1 + arr2}")
print(f"Resta (arr1 - arr2): {arr1 - arr2}")
print(f"Multiplicación (arr1 * arr2): {arr1 * arr2}")
print(f"División (arr2 / arr1): {arr2 / arr1}")
print(f"Potencia (arr1 ** 2): {arr1 ** 2}")

# Operaciones con escalares
print(f"\nOperación con escalar (arr1 * 5): {arr1 * 5}")
print(f"Operación con escalar (arr1 + 10): {arr1 + 10}")

print("\n" + "="*60)
print("FUNCIONES UNIVERSALES (ufuncs)")
print("="*60)

datos = np.array([1, 4, 9, 16, 25])
print(f"\nArray original: {datos}")

print(f"Raíz cuadrada: {np.sqrt(datos)}")

# Exponencial con array visible
datos_exp = np.array([1, 2, 3])
print(f"\nArray para exponencial: {datos_exp}")
print(f"Exponencial (e^x): {np.exp(datos_exp)}")

print(f"\nLogaritmo natural de {datos}:\n {np.log(datos)}")

# Funciones trigonométricas con redondeo para evitar errores de precisión
angulos = np.array([0, np.pi/2, np.pi])
print(f"\nÁngulos en radianes:\n {angulos}")
print(f"  → 0, π/2 ({np.pi/2:.4f}), π ({np.pi:.4f})")

# Redondear para eliminar errores de precisión de punto flotante
senos = np.round(np.sin(angulos), 10)
cosenos = np.round(np.cos(angulos), 10)

print(f"Seno: {senos}")
print(f"  → sin(0)=0, sin(π/2)=1, sin(π)=0")
print(f"Coseno: {cosenos}")
print(f"  → cos(0)=1, cos(π/2)=0, cos(π)=-1")

print("\n" + "="*60)
print("FUNCIONES DE AGREGACIÓN")
print("="*60)

numeros = np.array([5, 12, 3, 18, 7, 25, 9, 14])
print(f"\nArray: {numeros}")

print(f"\nSuma total: {np.sum(numeros)}")
print(f"Promedio (mean): {np.mean(numeros)}")
print(f"Desviación estándar (std): {np.std(numeros):.2f}")
print(f"Mínimo: {np.min(numeros)}")
print(f"Máximo: {np.max(numeros)}")
print(f"Índice del mínimo: {np.argmin(numeros)} → valor: {numeros[np.argmin(numeros)]}")
print(f"Índice del máximo: {np.argmax(numeros)} → valor: {numeros[np.argmax(numeros)]}")

print("\n" + "="*60)
print("OPERACIONES POR EJE (AXIS)")
print("="*60)

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\nMatriz:")
print(matriz)

print(f"\nSuma total (axis=None): {np.sum(matriz)}")
print(f"Suma por columnas (axis=0): {np.sum(matriz, axis=0)}")
print(f"Suma por filas (axis=1): {np.sum(matriz, axis=1)}")

print(f"\nPromedio por columnas (axis=0): {np.mean(matriz, axis=0)}")
print(f"Promedio por filas (axis=1): {np.mean(matriz, axis=1)}")

# Retomando el ejemplo de temperaturas del Ejercicio 1
temperaturas = np.array([[22, 24, 23, 25, 26, 24, 23],
                         [18, 19, 20, 19, 21, 20, 19],
                         [30, 32, 31, 33, 34, 32, 31],
                         [15, 16, 15, 17, 18, 16, 15]])


OPERACIONES ELEMENTO A ELEMENTO

Array 1: [1 2 3 4]
Array 2: [10 20 30 40]

Suma (arr1 + arr2): [11 22 33 44]
Resta (arr1 - arr2): [ -9 -18 -27 -36]
Multiplicación (arr1 * arr2): [ 10  40  90 160]
División (arr2 / arr1): [10. 10. 10. 10.]
Potencia (arr1 ** 2): [ 1  4  9 16]

Operación con escalar (arr1 * 5): [ 5 10 15 20]
Operación con escalar (arr1 + 10): [11 12 13 14]

FUNCIONES UNIVERSALES (ufuncs)

Array original: [ 1  4  9 16 25]
Raíz cuadrada: [1. 2. 3. 4. 5.]

Array para exponencial: [1 2 3]
Exponencial (e^x): [ 2.71828183  7.3890561  20.08553692]

Logaritmo natural de [ 1  4  9 16 25]:
 [0.         1.38629436 2.19722458 2.77258872 3.21887582]

Ángulos en radianes:
 [0.         1.57079633 3.14159265]
  → 0, π/2 (1.5708), π (3.1416)
Seno: [0. 1. 0.]
  → sin(0)=0, sin(π/2)=1, sin(π)=0
Coseno: [ 1.  0. -1.]
  → cos(0)=1, cos(π/2)=0, cos(π)=-1

FUNCIONES DE AGREGACIÓN

Array: [ 5 12  3 18  7 25  9 14]

Suma total: 93
Promedio (mean): 11.625
Desviación estándar (std): 6.82
Mínimo: 3


## **5. Broadcasting (Difusión)**

### ¿Qué es Broadcasting?

**Broadcasting** (difusión o propagación) es una técnica de NumPy que permite realizar operaciones aritméticas entre arrays de **diferentes formas** (shapes) sin necesidad de copiar datos explícitamente.

En lugar de tener que hacer que los arrays tengan exactamente las mismas dimensiones, NumPy automáticamente "estira" o "replica" el array más pequeño para que coincida con el más grande.

### Reglas de Broadcasting

NumPy compara las dimensiones de los arrays **de derecha a izquierda**. Dos dimensiones son compatibles cuando:

1. Son exactamente iguales, **O**
2. Una de ellas es 1

### Ejemplos de Broadcasting Compatible
```
Array A:      (3, 4)
Array B:      (3, 4)  ✅ Mismas dimensiones

Array A:      (3, 4)
Array B:         (4)  ✅ B se expande a (1, 4) → (3, 4)

Array A:      (3, 4)
Array B:      (3, 1)  ✅ B se expande de (3, 1) → (3, 4)

Array A:      (3, 4, 5)
Array B:         (4, 5)  ✅ B se expande a (1, 4, 5) → (3, 4, 5)
```

### Ejemplo NO Compatible
```
Array A:      (3, 4)
Array B:      (3, 5)  ❌ Las últimas dimensiones no coinciden (4 vs 5)
```

### ¿Por qué es útil en IA?

- **Normalización de datos**: Restar la media y dividir por la desviación estándar
- **Operaciones por lotes (batches)**: Aplicar la misma transformación a múltiples ejemplos
- **Eficiencia**: No se duplican datos en memoria, solo se ajusta la forma de acceso

In [8]:
print("="*60)
print("BROADCASTING - EJEMPLOS BÁSICOS")
print("="*60)

# Ejemplo 1: Escalar con array
print("\n" + "="*60)
print("1. Escalar con array:")
print("="*60)
arr = np.array([1, 2, 3, 4])
escalar = 10

print(f"\n   Array: {arr}, shape: {arr.shape}")
print(f"   Escalar: {escalar}")
print(f"   Resultado (arr + escalar): {arr + escalar}")
print("   → El escalar se 'expande' a [10, 10, 10, 10]")

# Ejemplo 2: Array 1D con array 2D
print("\n" + "="*60)
print("2. Array 1D con array 2D:")
print("="*60)
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])

print(f"\n   Matriz shape: {matriz.shape}")
print(matriz)
print(f"\n   Vector shape: {vector.shape}")
print(f"   {vector}")

resultado = matriz + vector
print(f"\n   Resultado (matriz + vector), shape: {resultado.shape}")
print(resultado)
print("   → El vector se 'expande' a cada fila de la matriz")

# Ejemplo 3: Columna con matriz
print("\n" + "="*60)
print("3. Broadcasting con columna:")
print("="*60)

columna = np.array([[1],
                    [2],
                    [3]])

print(f"\n   Matriz shape: {matriz.shape}")
print(matriz)
print(f"\n   Columna shape: {columna.shape}")
print(columna)

resultado_col = matriz + columna
print(f"\n   Resultado (matriz + columna), shape: {resultado_col.shape}")
print(resultado_col)
print("   → La columna se 'expande' a todas las columnas de la matriz")




BROADCASTING - EJEMPLOS BÁSICOS

1. Escalar con array:

   Array: [1 2 3 4], shape: (4,)
   Escalar: 10
   Resultado (arr + escalar): [11 12 13 14]
   → El escalar se 'expande' a [10, 10, 10, 10]

2. Array 1D con array 2D:

   Matriz shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

   Vector shape: (3,)
   [10 20 30]

   Resultado (matriz + vector), shape: (3, 3)
[[11 22 33]
 [14 25 36]
 [17 28 39]]
   → El vector se 'expande' a cada fila de la matriz

3. Broadcasting con columna:

   Matriz shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

   Columna shape: (3, 1)
[[1]
 [2]
 [3]]

   Resultado (matriz + columna), shape: (3, 3)
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
   → La columna se 'expande' a todas las columnas de la matriz


## Ejercicio 2: Normalización de Datos

### Contexto

En Machine Learning, es común normalizar datasets para que todas las características (features) tengan una escala similar. Esto ayuda a que los algoritmos converjan más rápido y funcionen mejor.

Imagina que tienes datos de estudiantes con tres características:
- **Edad** (en años): rango típico 18-25
- **Calificación** (0-100): rango típico 0-100
- **Horas de estudio** (por semana): rango típico 0-40

Como puedes ver, las escalas son muy diferentes. La normalización Min-Max transforma todos los valores al rango [0, 1].

### Fórmula de Normalización Min-Max

Para cada característica (columna):
```
valor_normalizado = (valor - mínimo) / (máximo - mínimo)
```

### Instrucciones

Dado el siguiente dataset:
```python
estudiantes = np.array([[20, 85, 15],   # Estudiante 1
                        [22, 90, 20],   # Estudiante 2
                        [19, 78, 12],   # Estudiante 3
                        [25, 95, 25],   # Estudiante 4
                        [18, 70, 10]])  # Estudiante 5
# Columnas: [Edad, Calificación, Horas de estudio]
```

**Tareas a realizar:**

1. Calcular el valor mínimo de cada característica (columna) usando `np.min()` con el eje apropiado
2. Calcular el valor máximo de cada característica (columna) usando `np.max()` con el eje apropiado
3. Aplicar la fórmula de normalización Min-Max usando broadcasting
4. Verificar que todos los valores normalizados estén entre 0 y 1


In [10]:
print("="*60)
print("SOLUCIÓN - EJERCICIO 2")
print("="*60)

# Datos del ejercicio
estudiantes = np.array([[20, 85, 15],   # Estudiante 1
                        [22, 90, 20],   # Estudiante 2
                        [19, 78, 12],   # Estudiante 3
                        [25, 95, 25],   # Estudiante 4
                        [18, 70, 10]])  # Estudiante 5

print("\nDataset original (5 estudiantes × 3 características):")
print("Columnas: [Edad, Calificación, Horas de estudio]")
print(estudiantes)
print(f"Shape: {estudiantes.shape}")

print("\n" + "-"*60)
print("Tarea 1: Calcular mínimo por característica")
print("-"*60)
minimos = np.min(estudiantes, axis=0)
print(f"Mínimos: {minimos}")
print(f"  → Edad mínima: {minimos[0]}")
print(f"  → Calificación mínima: {minimos[1]}")
print(f"  → Horas mínimas: {minimos[2]}")
print(f"Shape de mínimos: {minimos.shape}")

print("\n" + "-"*60)
print("Tarea 2: Calcular máximo por característica")
print("-"*60)
maximos = np.max(estudiantes, axis=0)
print(f"Máximos: {maximos}")
print(f"  → Edad máxima: {maximos[0]}")
print(f"  → Calificación máxima: {maximos[1]}")
print(f"  → Horas máximas: {maximos[2]}")
print(f"Shape de máximos: {maximos.shape}")

print("\n" + "-"*60)
print("Tarea 3: Aplicar normalización Min-Max con broadcasting")
print("-"*60)
# Fórmula: (valor - min) / (max - min)
estudiantes_normalizados = (estudiantes - minimos) / (maximos - minimos)

print("\nDataset normalizado:")
print(estudiantes_normalizados)

print("\nBroadcasting en acción:")
print(f"   estudiantes shape: {estudiantes.shape} (5, 3)")
print(f"   minimos shape: {minimos.shape} (3,)")
print(f"   maximos shape: {maximos.shape} (3,)")
print("   → Los vectores se 'expanden' automáticamente a cada fila")

print("\n" + "-"*60)
print("Tarea 4: Verificar que los valores estén entre 0 y 1")
print("-"*60)
print(f"Mínimo en dataset normalizado: {np.min(estudiantes_normalizados)}")
print(f"Máximo en dataset normalizado: {np.max(estudiantes_normalizados)}")

# Verificar por columna
print("\nMínimos por característica normalizada:")
print(np.min(estudiantes_normalizados, axis=0))
print("Máximos por característica normalizada:")
print(np.max(estudiantes_normalizados, axis=0))



SOLUCIÓN - EJERCICIO 2

Dataset original (5 estudiantes × 3 características):
Columnas: [Edad, Calificación, Horas de estudio]
[[20 85 15]
 [22 90 20]
 [19 78 12]
 [25 95 25]
 [18 70 10]]
Shape: (5, 3)

------------------------------------------------------------
Tarea 1: Calcular mínimo por característica
------------------------------------------------------------
Mínimos: [18 70 10]
  → Edad mínima: 18
  → Calificación mínima: 70
  → Horas mínimas: 10
Shape de mínimos: (3,)

------------------------------------------------------------
Tarea 2: Calcular máximo por característica
------------------------------------------------------------
Máximos: [25 95 25]
  → Edad máxima: 25
  → Calificación máxima: 95
  → Horas máximas: 25
Shape de máximos: (3,)

------------------------------------------------------------
Tarea 3: Aplicar normalización Min-Max con broadcasting
------------------------------------------------------------

Dataset normalizado:
[[0.28571429 0.6        0.33333333]
 

## **6. Álgebra Lineal Básica para IA**

### ¿Por qué Álgebra Lineal en IA?

Las redes neuronales y la mayoría de algoritmos de Machine Learning se basan fundamentalmente en operaciones de álgebra lineal:

- **Forward propagation** (propagación hacia adelante): Multiplicaciones matriciales
- **Transformaciones lineales**: Cambios de espacio vectorial
- **Pesos y sesgos**: Representados como matrices y vectores

### Operaciones Fundamentales

#### 1. Producto Punto (Dot Product)

El **producto punto** (dot product) entre dos vectores produce un escalar:
```
[a, b, c] · [x, y, z] = a*x + b*y + c*z
```

**Función:** `np.dot(vector1, vector2)`

#### 2. Producto Matricial (Matrix Multiplication)

El **producto matricial** es fundamental en redes neuronales. Para multiplicar matrices A(m×n) y B(n×p):

- El número de columnas de A debe ser igual al número de filas de B
- El resultado es una matriz de dimensión (m×p)

**Funciones:**
- `np.dot(matriz1, matriz2)`
- `np.matmul(matriz1, matriz2)`
- `matriz1 @ matriz2` (operador @, recomendado desde Python 3.5)

**Importante:** El operador `*` hace multiplicación **elemento a elemento**, NO matricial.

#### 3. Transpose (Transpuesta)

La **transpuesta** de una matriz intercambia filas por columnas:
```
Original:     Transpuesta:
[1, 2, 3]     [1, 4]
[4, 5, 6]  →  [2, 5]
              [3, 6]
```

**Función:** `matriz.T` o `np.transpose(matriz)`

### Aplicación en Redes Neuronales

Una operación básica en una capa de red neuronal es:
```
salida = activación(pesos @ entrada + bias)
```

Donde:
- `pesos`: Matriz de pesos (weights)
- `entrada`: Vector de entrada (input)
- `bias`: Vector de sesgos
- `@`: Producto matricial
- `activación`: Función no lineal (ReLU, sigmoid, etc.)

In [14]:
print("="*60)
print("PRODUCTO PUNTO (DOT PRODUCT)")
print("="*60)

# Vectores
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

print(f"\nVector A: {vector_a}")
print(f"Vector B: {vector_b}")

# Producto punto
dot_producto = np.dot(vector_a, vector_b)
print(f"\nProducto punto (A · B): {dot_producto}")
print(f"Cálculo: 1*4 + 2*5 + 3*6 = {1*4 + 2*5 + 3*6}")

print("\n" + "="*60)
print("PRODUCTO MATRICIAL (MATRIX MULTIPLICATION)")
print("="*60)

# Matrices
matriz_a = np.array([[1, 2],
                     [3, 4],
                     [5, 6]])

matriz_b = np.array([[7, 8, 9],
                     [10, 11, 12]])

print(f"\nMatriz A shape: {matriz_a.shape}")
print(matriz_a)

print(f"\nMatriz B shape: {matriz_b.shape}")
print(matriz_b)

# Producto matricial usando diferentes métodos
producto_dot = np.dot(matriz_a, matriz_b)
producto_matmul = np.matmul(matriz_a, matriz_b)
producto_operador = matriz_a @ matriz_b

print(f"\nProducto A @ B, shape: {producto_dot.shape}")
print(producto_dot)

print("\nVerificación - Todos los métodos dan el mismo resultado:")
print(f"np.dot == np.matmul: {np.array_equal(producto_dot, producto_matmul)}")
print(f"np.dot == @: {np.array_equal(producto_dot, producto_operador)}")

# Comparación con multiplicación elemento a elemento
print("\nDIFERENCIA: Multiplicación elemento a elemento (*) vs matricial (@)")
cuadrados_a = np.array([[2, 3],
                        [4, 5]])
cuadrados_b = np.array([[1, 2],
                        [3, 4]])

print(f"\nMatriz A:\n{cuadrados_a}")
print(f"\nMatriz B:\n{cuadrados_b}")

print(f"\nMultiplicación elemento a elemento (A * B):")
print(cuadrados_a * cuadrados_b)

print(f"\nMultiplicación matricial (A @ B):")
print(cuadrados_a @ cuadrados_b)

print("\n" + "="*60)
print("TRANSPOSE (TRANSPUESTA)")
print("="*60)

matriz_original = np.array([[1, 2, 3],
                           [4, 5, 6]])

print(f"\nMatriz original shape: {matriz_original.shape}")
print(matriz_original)

matriz_transpuesta = matriz_original.T

print(f"\nMatriz transpuesta shape: {matriz_transpuesta.shape}")
print(matriz_transpuesta)




PRODUCTO PUNTO (DOT PRODUCT)

Vector A: [1 2 3]
Vector B: [4 5 6]

Producto punto (A · B): 32
Cálculo: 1*4 + 2*5 + 3*6 = 32

PRODUCTO MATRICIAL (MATRIX MULTIPLICATION)

Matriz A shape: (3, 2)
[[1 2]
 [3 4]
 [5 6]]

Matriz B shape: (2, 3)
[[ 7  8  9]
 [10 11 12]]

Producto A @ B, shape: (3, 3)
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

Verificación - Todos los métodos dan el mismo resultado:
np.dot == np.matmul: True
np.dot == @: True

DIFERENCIA: Multiplicación elemento a elemento (*) vs matricial (@)

Matriz A:
[[2 3]
 [4 5]]

Matriz B:
[[1 2]
 [3 4]]

Multiplicación elemento a elemento (A * B):
[[ 2  6]
 [12 20]]

Multiplicación matricial (A @ B):
[[11 16]
 [19 28]]

TRANSPOSE (TRANSPUESTA)

Matriz original shape: (2, 3)
[[1 2 3]
 [4 5 6]]

Matriz transpuesta shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


## **Ejercicio 3: Transformaciones con Álgebra Lineal**

### Contexto

Las transformaciones lineales son fundamentales para manipular datos. En este ejercicio trabajaremos con operaciones matriciales para transformar un conjunto de puntos en el espacio 2D.

Imagina que tienes un conjunto de puntos que representan coordenadas (x, y) y quieres aplicarles diferentes transformaciones geométricas usando matrices.

### Instrucciones

Dado el siguiente conjunto de puntos:
```python
# Cada columna es un punto [x, y]
puntos = np.array([[1, 2, 3, 4],
                   [1, 3, 2, 4]])
# 4 puntos: (1,1), (2,3), (3,2), (4,4)
```

Y las siguientes matrices de transformación:
```python
# Matriz de escalado (scale): multiplica coordenadas por 2
escala = np.array([[2, 0],
                   [0, 2]])

# Matriz de rotación 90° (rotation)
rotacion_90 = np.array([[0, -1],
                        [1, 0]])
```

**Tareas a realizar:**

1. Aplicar la transformación de escalado a los puntos usando producto matricial
2. Aplicar la transformación de rotación 90° a los puntos originales
3. Aplicar primero escalado y luego rotación (composición de transformaciones)
4. Calcular la transpuesta de la matriz de puntos y explicar qué representa



In [16]:
print("="*60)
print("SOLUCIÓN - EJERCICIO 3")
print("="*60)

# Datos del ejercicio
puntos = np.array([[1, 2, 3, 4],
                   [1, 3, 2, 4]])

escala = np.array([[2, 0],
                   [0, 2]])

rotacion_90 = np.array([[0, -1],
                        [1, 0]])

print("\nPuntos originales (cada columna es un punto [x, y]):")
print(puntos)
print(f"Shape: {puntos.shape}")
print("Puntos: (1,1), (2,3), (3,2), (4,4)")

print("\n" + "-"*60)
print("Tarea 1: Aplicar transformación de escalado")
print("-"*60)

print("\nMatriz de escalado:")
print(escala)

puntos_escalados = escala @ puntos
print(f"\nPuntos escalados (escala @ puntos):")
print(puntos_escalados)
print("Puntos transformados: (2,2), (4,6), (6,4), (8,8)")
print("→ Todas las coordenadas se multiplicaron por 2")

print("\n" + "-"*60)
print("Tarea 2: Aplicar rotación de 90°")
print("-"*60)

print("\nMatriz de rotación 90°:")
print(rotacion_90)

puntos_rotados = rotacion_90 @ puntos
print(f"\nPuntos rotados (rotacion_90 @ puntos):")
print(puntos_rotados)
print("Puntos transformados: (-1,1), (-3,2), (-2,3), (-4,4)")
print("→ Los puntos rotaron 90° en sentido antihorario")

print("\n" + "-"*60)
print("Tarea 3: Composición - Primero escalar, luego rotar")
print("-"*60)

# Opción 1: Aplicar transformaciones secuencialmente
paso1 = escala @ puntos
print("\nPaso 1 - Escalar:")
print(paso1)

paso2 = rotacion_90 @ paso1
print("\nPaso 2 - Rotar los puntos escalados:")
print(paso2)

# Opción 2: Combinar matrices primero (más eficiente)
print("\nAlternativa - Combinar transformaciones en una sola matriz:")
transformacion_combinada = rotacion_90 @ escala
print("Matriz combinada (rotacion_90 @ escala):")
print(transformacion_combinada)

puntos_transformados = transformacion_combinada @ puntos
print("\nPuntos con transformación combinada:")
print(puntos_transformados)

print("\nVerificación - Ambos métodos dan el mismo resultado:")
print(f"Resultados iguales: {np.array_equal(paso2, puntos_transformados)}")

print("\n" + "-"*60)
print("Tarea 4: Transpuesta de la matriz de puntos")
print("-"*60)

print("\nMatriz de puntos original:")
print(puntos)
print(f"Shape: {puntos.shape} → 2 filas (x, y), 4 columnas (puntos)")

puntos_transpuesta = puntos.T
print("\nMatriz de puntos transpuesta:")
print(puntos_transpuesta)
print(f"Shape: {puntos_transpuesta.shape} → 4 filas (puntos), 2 columnas (x, y)")

print("\nInterpretación:")
print("   - Original: cada COLUMNA es un punto")
print("   - Transpuesta: cada FILA es un punto")
print("   - La transpuesta cambia la organización de los datos")


SOLUCIÓN - EJERCICIO 3

Puntos originales (cada columna es un punto [x, y]):
[[1 2 3 4]
 [1 3 2 4]]
Shape: (2, 4)
Puntos: (1,1), (2,3), (3,2), (4,4)

------------------------------------------------------------
Tarea 1: Aplicar transformación de escalado
------------------------------------------------------------

Matriz de escalado:
[[2 0]
 [0 2]]

Puntos escalados (escala @ puntos):
[[2 4 6 8]
 [2 6 4 8]]
Puntos transformados: (2,2), (4,6), (6,4), (8,8)
→ Todas las coordenadas se multiplicaron por 2

------------------------------------------------------------
Tarea 2: Aplicar rotación de 90°
------------------------------------------------------------

Matriz de rotación 90°:
[[ 0 -1]
 [ 1  0]]

Puntos rotados (rotacion_90 @ puntos):
[[-1 -3 -2 -4]
 [ 1  2  3  4]]
Puntos transformados: (-1,1), (-3,2), (-2,3), (-4,4)
→ Los puntos rotaron 90° en sentido antihorario

------------------------------------------------------------
Tarea 3: Composición - Primero escalar, luego rotar
------

## **7. Consejos y Mejores Prácticas**

### Evitar Loops (Bucles) Cuando Sea Posible

NumPy está optimizado para **operaciones vectorizadas**. Siempre que puedas, evita usar bucles `for` y `while`.

**❌ Evitar:**
```python
resultado = []
for i in range(len(array)):
    resultado.append(array[i] * 2)
```

**✅ Preferir:**
```python
resultado = array * 2
```

### Usar el "Axis" Correcto

Entender el parámetro `axis` es crucial:
- `axis=0`: Opera a lo largo de las **filas** (hacia abajo, resultado por columna)
- `axis=1`: Opera a lo largo de las **columnas** (hacia la derecha, resultado por fila)
- `axis=None`: Opera sobre todo el array (default en muchas funciones)

### Verificar Shapes Frecuentemente

Los errores de dimensiones son comunes. Usa `array.shape` constantemente para verificar:
```python
print(f"Shape: {array.shape}")
```

### Cuidado con Copias vs Vistas (Views)

- **Slicing** crea una **vista** (view): modificar la vista modifica el original
- Usa `.copy()` cuando necesites una copia independiente
```python
vista = array[0:3]        # Vista - modifica el original
copia = array[0:3].copy() # Copia independiente
```

### Aprovechar Broadcasting

En lugar de expandir manualmente arrays, deja que NumPy lo haga automáticamente con broadcasting.

### Tipos de Datos (dtypes)

Especificar el tipo de dato puede ahorrar memoria y mejorar rendimiento:
```python
array_int = np.array([1, 2, 3], dtype=np.int32)
array_float = np.array([1, 2, 3], dtype=np.float64)
```

### Recursos para Profundizar

- **Documentación oficial de NumPy:** https://numpy.org/doc/
- **NumPy Tutorial oficial:** https://numpy.org/doc/stable/user/quickstart.html
- **NumPy for Absolute Beginners:** https://numpy.org/doc/stable/user/absolute_beginners.html
- **From Python to NumPy (libro gratuito):** https://www.labri.fr/perso/nrougier/from-python-to-numpy/

### Funciones Útiles Adicionales

Algunas funciones que no cubrimos pero son muy útiles:

- `np.where()`: Selección condicional
- `np.concatenate()`, `np.vstack()`, `np.hstack()`: Combinar arrays
- `np.reshape()`: Cambiar la forma de un array
- `np.random`: Módulo completo para números aleatorios
- `np.linalg`: Módulo de álgebra lineal avanzada